"""Read API + admin surface.

This service never calls the model on the read path — the world is pre-generated by the
worker, so an unbounded number of viewers costs nothing. The only synchronous spend is
/api/poke, which is why it carries its own hard daily cap.

Every route declares a response model. A shape change then breaks here, loudly, instead of
reaching the frontend as a field that silently reads `undefined`.
"""
from __future__ import annotations

import hmac
import json
import re
from uuid import UUID

from fastapi import Depends, FastAPI, HTTPException, Request, Response
from fastapi.middleware.cors import CORSMiddleware

from charsocial import db
from charsocial.config import CONFIG, assert_safe_to_spend
from charsocial.models import (
    AdminCharacter,
    AdminCharactersOut,
    Author,
    BudgetOut,
    CharacterOut,
    CharactersOut,
    DraftIn,
    DraftOut,
    FeedOut,
    Headline,
    Health,
    HeatOut,
    HeatPair,
    Liker,
    LikesOut,
    LoginIn,
    Ok,
    PatchIn,
    PeopleOut,
    Person,
    PokeIn,
    PokeOut,
    PostOut,
    Profile,
    ProfileOut,
    StatsOut,
    TickRow,
    TickStats,
    UsageOut,
    WorldOut,
)
from charsocial.queries import SQL
from charsocial.worker import characters as chars
from charsocial.worker import tick as tick_module

# Fails fast if the README's dev secrets are still set while pointed at the real API.
assert_safe_to_spend()

app = FastAPI(title="Character Social", docs_url=None, redoc_url=None)
app.add_middleware(
    CORSMiddleware,
    allow_origins=CONFIG.cors_origin_list,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

SESSION_COOKIE = "cs_session"


# ------------------------------------------------------------------------------- auth


def _session_value() -> str:
    return hmac.new(CONFIG.site_password.encode(), b"charsocial", "sha256").hexdigest()[:32]


def require_visitor(request: Request) -> None:
    if not hmac.compare_digest(request.cookies.get(SESSION_COOKIE, ""), _session_value()):
        raise HTTPException(status_code=401, detail="password required")


def require_admin(request: Request) -> None:
    token = request.headers.get("x-admin-token", "")
    if not hmac.compare_digest(token, CONFIG.admin_token):
        raise HTTPException(status_code=403, detail="admin token required")


@app.post("/api/login", response_model=Ok)
def login(body: LoginIn, response: Response) -> Ok:
    if not hmac.compare_digest(body.password, CONFIG.site_password):
        raise HTTPException(status_code=401, detail="wrong password")
    # "none" so the cookie survives a tunnelled API on a different origin than the web app.
    # It costs the browser's cross-site CSRF protection, which the password gate does not
    # replace — tighten to "lax" whenever the two are served same-site.
    response.set_cookie(
        SESSION_COOKIE, _session_value(), httponly=True, samesite="none", secure=True,
        max_age=60 * 60 * 24 * 30,
    )
    return Ok()


@app.get("/api/health", response_model=Health)
def health() -> Health:
    return Health(ok=True, provider=CONFIG.llm_provider, world=CONFIG.world_id)


# ------------------------------------------------------------------------------- feed




def _post_out(row) -> PostOut:
    return PostOut(
        id=str(row["id"]),
        body=row["body"],
        createdAt=row["created_at"],
        likeCount=row["like_count"],
        replyCount=row["reply_count"],
        parentId=str(row["parent_id"]) if row.get("parent_id") else None,
        replyingTo=row.get("replying_to"),
        author=Author(
            handle=row.get("handle") or "guest",
            name=row.get("name") or "Guest",
            avatarSeed=row.get("avatar_seed") or "guest",
            avatarUrl=row.get("avatar_url"),
            # A human poke has no character row, so there is no profile to open.
            isCharacter=row.get("handle") is not None,
            # Drives the parody badge. PLAN §12 calls the watermark the control that
            # makes a leaked screenshot a non-event.
            isRealPerson=bool(row.get("is_real_person")),
        ),
        headline=(
            Headline(title=row["headline_title"], url=row["headline_url"])
            if row.get("headline_title")
            else None
        ),
    )


@app.get("/api/feed", response_model=FeedOut, dependencies=[Depends(require_visitor)])
def feed(limit: int = 40, offset: int = 0) -> FeedOut:
    with db.cursor() as cur:
        cur.execute(
            SQL["feed"],
            {"world": CONFIG.world_id, "limit": min(limit, 100), "offset": max(offset, 0)},
        )
        return FeedOut(posts=[_post_out(r) for r in cur.fetchall()])


@app.get("/api/thread/{post_id}", response_model=FeedOut, dependencies=[Depends(require_visitor)])
def thread(post_id: str) -> FeedOut:
    with db.cursor() as cur:
        cur.execute(SQL["thread"], {"post": post_id})
        rows = cur.fetchall()
    if not rows:
        raise HTTPException(status_code=404, detail="not found")
    return FeedOut(posts=[_post_out(r) for r in rows])




@app.get(
    "/api/posts/{post_id}/likes",
    response_model=LikesOut,
    dependencies=[Depends(require_visitor)],
)
def post_likes(post_id: UUID, limit: int = 50) -> LikesOut:
    with db.cursor() as cur:
        cur.execute(SQL["post_likes"], {"post": post_id, "limit": min(limit, 200)})
        return LikesOut(
            likers=[
                Liker(
                    handle=r["handle"],
                    name=r["name"],
                    avatarSeed=r["avatar_seed"],
                    avatarUrl=r["avatar_url"],
                    likedAt=r["created_at"],
                )
                for r in cur.fetchall()
            ]
        )




@app.get("/api/heat", response_model=HeatOut, dependencies=[Depends(require_visitor)])
def heat_board(limit: int = 8) -> HeatOut:
    """Powers the heat board. This is the engine made visible: heat rises when two
    characters interact and decays every tick, so feuds form and cool on their own."""
    with db.cursor() as cur:
        cur.execute(SQL["heat"], {"world": CONFIG.world_id, "limit": min(limit, 20)})
        rows = cur.fetchall()
    top = max((r["heat"] for r in rows), default=1) or 1
    return HeatOut(
        pairs=[
            HeatPair(
                a=r["a_name"],
                b=r["b_name"],
                heat=round(r["heat"], 2),
                share=round(r["heat"] / top, 3),
                mood=(
                    "hostile" if r["sentiment"] < -1 else "warm" if r["sentiment"] > 1 else "neutral"
                ),
                threadId=str(r["thread_id"]) if r.get("thread_id") else None,
            )
            for r in rows
        ]
    )


@app.get("/api/world", response_model=WorldOut, dependencies=[Depends(require_visitor)])
def world() -> WorldOut:
    with db.cursor() as cur:
        cur.execute(SQL["last_finished_tick"])
        last = cur.fetchone()
        cur.execute(SQL["post_count"], {"world": CONFIG.world_id})
        posts = db.one(cur)["n"]
        cur.execute(SQL["active_character_count"], {"world": CONFIG.world_id})
        active = db.one(cur)["n"]
    return WorldOut(
        tick=last["id"] if last else 0,
        lastTickAt=last["started_at"] if last else None,
        intervalMinutes=CONFIG.tick_interval_minutes,
        posts=posts,
        characters=active,
    )


@app.get("/api/characters", response_model=CharactersOut, dependencies=[Depends(require_visitor)])
def character_list() -> CharactersOut:
    with db.cursor() as cur:
        cur.execute(SQL["character_list"], {"world": CONFIG.world_id})
        return CharactersOut(
            characters=[CharacterOut.model_validate(dict(r)) for r in cur.fetchall()]
        )


# ---------------------------------------------------------------------------- profile




@app.get("/api/profile/{handle}", response_model=ProfileOut, dependencies=[Depends(require_visitor)])
def profile(handle: str, limit: int = 50) -> ProfileOut:
    """Both tabs in one response. They come from the same rows and switching between them
    shouldn't hit the network — the world only changes on a tick."""
    handle = handle.lstrip("@").lower()
    args = {"handle": handle, "world": CONFIG.world_id, "limit": min(limit, 100)}
    with db.cursor() as cur:
        cur.execute(SQL["profile"], args)
        row = cur.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="no such character")

        cur.execute(SQL["profile_posts"], {**args, "top_level": True})
        posts = [_post_out(r) for r in cur.fetchall()]
        cur.execute(SQL["profile_posts"], {**args, "top_level": False})
        replies = [_post_out(r) for r in cur.fetchall()]

    return ProfileOut(
        profile=Profile(
            handle=row["handle"],
            name=row["name"],
            avatarSeed=row["avatar_seed"],
            avatarUrl=row["avatar_url"],
            isRealPerson=row["is_real_person"],
            status=row["status"],
            bio=row["bio"],
            opensPerDay=row["opens_per_day"],
            joinedAt=row["joined_at"],
            postCount=row["post_count"],
            replyCount=row["reply_count"],
            likesReceived=row["likes_received"],
            followerCount=row["follower_count"],
            followingCount=row["following_count"],
        ),
        posts=posts,
        replies=replies,
    )




def _follows(handle: str, direction: str, limit: int) -> PeopleOut:
    with db.cursor() as cur:
        cur.execute(
            SQL[direction],
            {"handle": handle, "world": CONFIG.world_id, "limit": min(limit, 200)},
        )
        return PeopleOut(
            people=[
                Person(
                    handle=r["handle"],
                    name=r["name"],
                    avatarSeed=r["avatar_seed"],
                    avatarUrl=r["avatar_url"],
                    bio=r["bio"],
                )
                for r in cur.fetchall()
            ]
        )


@app.get(
    "/api/profile/{handle}/followers",
    response_model=PeopleOut,
    dependencies=[Depends(require_visitor)],
)
def followers(handle: str, limit: int = 100) -> PeopleOut:
    return _follows(handle, "followers", limit)


@app.get(
    "/api/profile/{handle}/following",
    response_model=PeopleOut,
    dependencies=[Depends(require_visitor)],
)
def following(handle: str, limit: int = 100) -> PeopleOut:
    return _follows(handle, "following", limit)


# ------------------------------------------------------------------------------- poke


@app.post("/api/poke", response_model=PokeOut, dependencies=[Depends(require_visitor)])
def poke(body: PokeIn) -> PokeOut:
    """A human reply. It enters the world as a post plus a notification — it does NOT
    trigger a generation. The character answers on the next tick, from the same budget as
    everyone else, which is what keeps this path from being a way to spend without limit.
    """
    # Both fields interpolate into a character's next prompt under markdown headings that
    # are structurally identical to the WORLD_RULES sections, and any poison persists via
    # memory_notes. Collapsing newlines removes the ability to forge a heading.
    if not CONFIG.poke_enabled:
        raise HTTPException(status_code=404, detail="not found")

    clean = " ".join(body.body.split())[:280]
    display_name = re.sub(r"[^a-z0-9_]", "", body.display_name.lower())[:24] or "guest"
    if not clean:
        raise HTTPException(status_code=400, detail="empty")

    with db.cursor() as cur:
        cur.execute(SQL["human_posts_today"])
        if db.one(cur)["n"] >= CONFIG.poke_daily_cap:
            raise HTTPException(status_code=429, detail="daily poke limit reached")

        cur.execute(SQL["poke_target"], {"post": body.post_id})
        target = cur.fetchone()
        if not target:
            raise HTTPException(status_code=404, detail="no such post")

        cur.execute(
            SQL["insert_human_poke"],
            {
                "world": CONFIG.world_id, "author": display_name, "body": clean,
                "parent": body.post_id, "root": target["root"],
                "character": target["character_id"],
            },
        )
        new_id = db.one(cur)["id"]
    return PokeOut(ok=True, id=str(new_id))


# ------------------------------------------------------------------------------ admin


@app.post(
    "/api/admin/characters/draft", response_model=DraftOut, dependencies=[Depends(require_admin)]
)
def draft_character(body: DraftIn) -> DraftOut:
    with db.cursor() as cur:
        result = chars.draft(cur, body.name, body.context, body.notes, body.source_material)
    if result is None:
        raise HTTPException(status_code=503, detail="no drafting provider (offline mode)")
    return DraftOut.model_validate(result)


@app.patch("/api/admin/characters/{character_id}", response_model=Ok,
           dependencies=[Depends(require_admin)])
def patch_character(character_id: str, body: PatchIn) -> Ok:
    with db.cursor() as cur:
        if body.persona_card is not None:
            cur.execute(
                "UPDATE characters SET persona_card = %s WHERE id = %s",
                (json.dumps(body.persona_card), character_id),
            )
        if body.engagement_profile is not None:
            cur.execute(
                "UPDATE characters SET engagement_profile = %s WHERE id = %s",
                (json.dumps(body.engagement_profile), character_id),
            )
        if body.status:
            chars.set_status(cur, character_id, body.status)
    return Ok()


@app.get(
    "/api/admin/characters", response_model=AdminCharactersOut, dependencies=[Depends(require_admin)]
)
def admin_characters() -> AdminCharactersOut:
    with db.cursor() as cur:
        cur.execute(SQL["admin_characters"], {"world": CONFIG.world_id})
        return AdminCharactersOut(
            characters=[AdminCharacter.model_validate(dict(r)) for r in cur.fetchall()]
        )


@app.post("/api/admin/tick", response_model=TickStats, dependencies=[Depends(require_admin)])
def admin_tick() -> TickStats:
    return TickStats.model_validate(tick_module.run())


@app.get("/api/admin/stats", response_model=StatsOut, dependencies=[Depends(require_admin)])
def admin_stats() -> StatsOut:
    with db.cursor() as cur:
        cur.execute(SQL["admin_totals"], {"world": CONFIG.world_id})
        totals = dict(db.one(cur))

        cur.execute(SQL["admin_recent_ticks"])
        recent = [TickRow.model_validate(dict(r)) for r in cur.fetchall()]

        # cache_read == 0 across collected batches is the ONLY signal that a silent cache
        # invalidator has crept in — there is no error for it.
        cur.execute(SQL["admin_usage"])
        usage = UsageOut.model_validate(dict(db.one(cur)))

    return StatsOut(
        **totals,
        usage=usage,
        recent_ticks=recent,
        budget=BudgetOut(
            tick_budget=CONFIG.tick_budget,
            interval_minutes=CONFIG.tick_interval_minutes,
            turns_per_day=round(CONFIG.ticks_per_day * CONFIG.tick_budget),
        ),
    )
