"""Read API + admin surface.

This service never calls the model on the read path — the world is pre-generated by the
worker, so an unbounded number of viewers costs nothing. The only synchronous spend is
/api/poke, which is why it carries its own hard daily cap.

Every route declares a response model. A shape change then breaks here, loudly, instead of
reaching the frontend as a field that silently reads `undefined`.
"""
from __future__ import annotations

import hmac
import json
import re
from uuid import UUID

from fastapi import Depends, FastAPI, HTTPException, Request, Response
from fastapi.middleware.cors import CORSMiddleware

from charsocial import db
from charsocial.config import CONFIG, assert_safe_to_spend
from charsocial.models import (
    AdminCharacter,
    AdminCharactersOut,
    Author,
    BudgetOut,
    CharacterOut,
    CharactersOut,
    DraftIn,
    DraftOut,
    FeedOut,
    Headline,
    Health,
    HeatOut,
    HeatPair,
    Liker,
    LikesOut,
    LoginIn,
    Ok,
    PatchIn,
    PokeIn,
    PokeOut,
    PostOut,
    StatsOut,
    TickRow,
    TickStats,
    UsageOut,
    WorldOut,
)
from charsocial.worker import characters as chars
from charsocial.worker import tick as tick_module

# Fails fast if the README's dev secrets are still set while pointed at the real API.
assert_safe_to_spend()

app = FastAPI(title="Character Social", docs_url=None, redoc_url=None)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

SESSION_COOKIE = "cs_session"


# ------------------------------------------------------------------------------- auth


def _session_value() -> str:
    return hmac.new(CONFIG.site_password.encode(), b"charsocial", "sha256").hexdigest()[:32]


def require_visitor(request: Request) -> None:
    if not hmac.compare_digest(request.cookies.get(SESSION_COOKIE, ""), _session_value()):
        raise HTTPException(status_code=401, detail="password required")


def require_admin(request: Request) -> None:
    token = request.headers.get("x-admin-token", "")
    if not hmac.compare_digest(token, CONFIG.admin_token):
        raise HTTPException(status_code=403, detail="admin token required")


@app.post("/api/login", response_model=Ok)
def login(body: LoginIn, response: Response) -> Ok:
    if not hmac.compare_digest(body.password, CONFIG.site_password):
        raise HTTPException(status_code=401, detail="wrong password")
    response.set_cookie(
        SESSION_COOKIE, _session_value(), httponly=True, samesite="lax", max_age=60 * 60 * 24 * 30
    )
    return Ok()


@app.get("/api/health", response_model=Health)
def health() -> Health:
    return Health(ok=True, provider=CONFIG.llm_provider, world=CONFIG.world_id)


# ------------------------------------------------------------------------------- feed

FEED_SQL = """
SELECT p.id, p.body, p.created_at, p.like_count, p.reply_count, p.heat,
       p.parent_id, p.quote_of_id,
       c.handle, c.name, c.avatar_seed, c.is_real_person,
       h.title AS headline_title, h.url AS headline_url
  FROM posts p
  LEFT JOIN characters c ON c.id = p.character_id
  LEFT JOIN headlines h  ON h.id = p.headline_id
 WHERE p.world_id = %(world)s AND p.parent_id IS NULL
 ORDER BY p.heat / (1 + extract(epoch FROM now() - p.created_at) / 3600.0) DESC,
          p.created_at DESC
 LIMIT %(limit)s OFFSET %(offset)s
"""

THREAD_SQL = """
SELECT p.id, p.body, p.created_at, p.like_count, p.reply_count, p.parent_id,
       c.handle, c.name, c.avatar_seed, c.is_real_person,
       h.title AS headline_title, h.url AS headline_url
  FROM posts p
  LEFT JOIN characters c ON c.id = p.character_id
  LEFT JOIN headlines h  ON h.id = p.headline_id
 WHERE coalesce(p.root_id, p.id) = (SELECT coalesce(root_id, id) FROM posts WHERE id = %s)
 ORDER BY p.created_at
"""


def _post_out(row) -> PostOut:
    return PostOut(
        id=str(row["id"]),
        body=row["body"],
        createdAt=row["created_at"],
        likeCount=row["like_count"],
        replyCount=row["reply_count"],
        parentId=str(row["parent_id"]) if row.get("parent_id") else None,
        author=Author(
            handle=row.get("handle") or "guest",
            name=row.get("name") or "Guest",
            avatarSeed=row.get("avatar_seed") or "guest",
            # Drives the parody badge. PLAN §12 calls the watermark the control that
            # makes a leaked screenshot a non-event.
            isRealPerson=bool(row.get("is_real_person")),
        ),
        headline=(
            Headline(title=row["headline_title"], url=row["headline_url"])
            if row.get("headline_title")
            else None
        ),
    )


@app.get("/api/feed", response_model=FeedOut, dependencies=[Depends(require_visitor)])
def feed(limit: int = 40, offset: int = 0) -> FeedOut:
    with db.cursor() as cur:
        cur.execute(
            FEED_SQL,
            {"world": CONFIG.world_id, "limit": min(limit, 100), "offset": max(offset, 0)},
        )
        return FeedOut(posts=[_post_out(r) for r in cur.fetchall()])


@app.get("/api/thread/{post_id}", response_model=FeedOut, dependencies=[Depends(require_visitor)])
def thread(post_id: str) -> FeedOut:
    with db.cursor() as cur:
        cur.execute(THREAD_SQL, (post_id,))
        rows = cur.fetchall()
    if not rows:
        raise HTTPException(status_code=404, detail="not found")
    return FeedOut(posts=[_post_out(r) for r in rows])


LIKES_SQL = """
SELECT c.handle, c.name, c.avatar_seed, l.created_at
  FROM likes l
  JOIN characters c ON c.id = l.character_id
 WHERE l.post_id = %(post)s
 ORDER BY l.created_at DESC
 LIMIT %(limit)s
"""


@app.get(
    "/api/posts/{post_id}/likes",
    response_model=LikesOut,
    dependencies=[Depends(require_visitor)],
)
def post_likes(post_id: UUID, limit: int = 50) -> LikesOut:
    with db.cursor() as cur:
        cur.execute(LIKES_SQL, {"post": post_id, "limit": min(limit, 200)})
        return LikesOut(
            likers=[
                Liker(
                    handle=r["handle"],
                    name=r["name"],
                    avatarSeed=r["avatar_seed"],
                    likedAt=r["created_at"],
                )
                for r in cur.fetchall()
            ]
        )


HEAT_SQL = """
SELECT a.name AS a_name, b.name AS b_name, r.heat, r.sentiment,
       coalesce(argued.root_id, liked.root_id) AS thread_id
  FROM relations r
  JOIN characters a ON a.id = r.character_id
  JOIN characters b ON b.id = r.other_id
  -- The hottest thread both of them actually posted in: the argument itself.
  LEFT JOIN LATERAL (
      SELECT coalesce(p.root_id, p.id) AS root_id
        FROM posts p
       WHERE p.world_id = a.world_id
         AND p.character_id IN (r.character_id, r.other_id)
       GROUP BY coalesce(p.root_id, p.id)
      HAVING bool_or(p.character_id = r.character_id)
         AND bool_or(p.character_id = r.other_id)
       ORDER BY max(p.heat) DESC
       LIMIT 1
  ) argued ON true
  -- Heat also rises on a like alone, so a pair can be hot with nothing said between them.
  LEFT JOIN LATERAL (
      SELECT coalesce(p.root_id, p.id) AS root_id
        FROM posts p
        JOIN likes l ON l.post_id = p.id AND l.character_id = r.character_id
       WHERE p.character_id = r.other_id
       ORDER BY p.heat DESC
       LIMIT 1
  ) liked ON true
 WHERE r.heat > 0.2 AND a.world_id = %s
 ORDER BY r.heat DESC LIMIT %s
"""


@app.get("/api/heat", response_model=HeatOut, dependencies=[Depends(require_visitor)])
def heat_board(limit: int = 8) -> HeatOut:
    """Powers the heat board. This is the engine made visible: heat rises when two
    characters interact and decays every tick, so feuds form and cool on their own."""
    with db.cursor() as cur:
        cur.execute(HEAT_SQL, (CONFIG.world_id, min(limit, 20)))
        rows = cur.fetchall()
    top = max((r["heat"] for r in rows), default=1) or 1
    return HeatOut(
        pairs=[
            HeatPair(
                a=r["a_name"],
                b=r["b_name"],
                heat=round(r["heat"], 2),
                share=round(r["heat"] / top, 3),
                mood=(
                    "hostile" if r["sentiment"] < -1 else "warm" if r["sentiment"] > 1 else "neutral"
                ),
                threadId=str(r["thread_id"]) if r.get("thread_id") else None,
            )
            for r in rows
        ]
    )


@app.get("/api/world", response_model=WorldOut, dependencies=[Depends(require_visitor)])
def world() -> WorldOut:
    with db.cursor() as cur:
        cur.execute(
            "SELECT id, started_at FROM ticks WHERE finished_at IS NOT NULL "
            "ORDER BY id DESC LIMIT 1"
        )
        last = cur.fetchone()
        cur.execute("SELECT count(*) AS n FROM posts WHERE world_id = %s", (CONFIG.world_id,))
        posts = cur.fetchone()["n"]
        cur.execute(
            "SELECT count(*) AS n FROM characters WHERE status='active' AND world_id = %s",
            (CONFIG.world_id,),
        )
        active = cur.fetchone()["n"]
    return WorldOut(
        tick=last["id"] if last else 0,
        lastTickAt=last["started_at"] if last else None,
        intervalMinutes=CONFIG.tick_interval_minutes,
        posts=posts,
        characters=active,
    )


@app.get("/api/characters", response_model=CharactersOut, dependencies=[Depends(require_visitor)])
def character_list() -> CharactersOut:
    with db.cursor() as cur:
        cur.execute(
            """
            SELECT c.handle, c.name, c.avatar_seed, c.status,
                   c.persona_card->>'bio' AS bio,
                   (c.engagement_profile->>'opens_per_day')::float AS opens_per_day,
                   (SELECT count(*) FROM posts p WHERE p.character_id = c.id) AS post_count,
                   (SELECT count(*) FROM follows f WHERE f.followee_id = c.id) AS follower_count
              FROM characters c
             WHERE c.world_id = %s AND c.status <> 'draft'
             ORDER BY follower_count DESC
            """,
            (CONFIG.world_id,),
        )
        return CharactersOut(
            characters=[CharacterOut.model_validate(dict(r)) for r in cur.fetchall()]
        )


# ------------------------------------------------------------------------------- poke


@app.post("/api/poke", response_model=PokeOut, dependencies=[Depends(require_visitor)])
def poke(body: PokeIn) -> PokeOut:
    """A human reply. It enters the world as a post plus a notification — it does NOT
    trigger a generation. The character answers on the next tick, from the same budget as
    everyone else, which is what keeps this path from being a way to spend without limit.
    """
    # Both fields interpolate into a character's next prompt under markdown headings that
    # are structurally identical to the WORLD_RULES sections, and any poison persists via
    # memory_notes. Collapsing newlines removes the ability to forge a heading.
    clean = " ".join(body.body.split())[:280]
    display_name = re.sub(r"[^a-z0-9_]", "", body.display_name.lower())[:24] or "guest"
    if not clean:
        raise HTTPException(status_code=400, detail="empty")

    with db.cursor() as cur:
        cur.execute(
            "SELECT count(*) AS n FROM posts "
            "WHERE author_human IS NOT NULL AND created_at > now() - interval '1 day'"
        )
        if cur.fetchone()["n"] >= CONFIG.poke_daily_cap:
            raise HTTPException(status_code=429, detail="daily poke limit reached")

        cur.execute(
            "SELECT character_id, coalesce(root_id, id) AS root FROM posts WHERE id = %s",
            (body.post_id,),
        )
        target = cur.fetchone()
        if not target:
            raise HTTPException(status_code=404, detail="no such post")

        cur.execute(
            """
            INSERT INTO posts (world_id, author_human, body, parent_id, root_id)
            VALUES (%s, %s, %s, %s, %s) RETURNING id
            """,
            (CONFIG.world_id, display_name, clean, body.post_id, target["root"]),
        )
        new_id = cur.fetchone()["id"]
        # A poke is a real child post, so the parent's rendered count must include it.
        cur.execute("UPDATE posts SET reply_count = reply_count + 1 WHERE id = %s", (body.post_id,))
        if target["character_id"]:
            cur.execute(
                "INSERT INTO notifications (character_id, post_id, kind) VALUES (%s, %s, 'human')",
                (target["character_id"], new_id),
            )
    return PokeOut(ok=True, id=str(new_id))


# ------------------------------------------------------------------------------ admin


@app.post(
    "/api/admin/characters/draft", response_model=DraftOut, dependencies=[Depends(require_admin)]
)
def draft_character(body: DraftIn) -> DraftOut:
    with db.cursor() as cur:
        result = chars.draft(cur, body.name, body.context, body.notes, body.source_material)
    if result is None:
        raise HTTPException(status_code=503, detail="no drafting provider (offline mode)")
    return DraftOut.model_validate(result)


@app.patch("/api/admin/characters/{character_id}", response_model=Ok,
           dependencies=[Depends(require_admin)])
def patch_character(character_id: str, body: PatchIn) -> Ok:
    with db.cursor() as cur:
        if body.persona_card is not None:
            cur.execute(
                "UPDATE characters SET persona_card = %s WHERE id = %s",
                (json.dumps(body.persona_card), character_id),
            )
        if body.engagement_profile is not None:
            cur.execute(
                "UPDATE characters SET engagement_profile = %s WHERE id = %s",
                (json.dumps(body.engagement_profile), character_id),
            )
        if body.status:
            chars.set_status(cur, character_id, body.status)
    return Ok()


@app.get(
    "/api/admin/characters", response_model=AdminCharactersOut, dependencies=[Depends(require_admin)]
)
def admin_characters() -> AdminCharactersOut:
    with db.cursor() as cur:
        cur.execute(
            "SELECT id, handle, name, status, persona_card, engagement_profile "
            "FROM characters WHERE world_id = %s ORDER BY created_at DESC",
            (CONFIG.world_id,),
        )
        return AdminCharactersOut(
            characters=[AdminCharacter.model_validate(dict(r)) for r in cur.fetchall()]
        )


@app.post("/api/admin/tick", response_model=TickStats, dependencies=[Depends(require_admin)])
def admin_tick() -> TickStats:
    return TickStats.model_validate(tick_module.run())


@app.get("/api/admin/stats", response_model=StatsOut, dependencies=[Depends(require_admin)])
def admin_stats() -> StatsOut:
    with db.cursor() as cur:
        cur.execute(
            """
            SELECT (SELECT count(*) FROM posts WHERE world_id = %(w)s) AS posts,
                   (SELECT count(*) FROM likes) AS likes,
                   (SELECT count(*) FROM characters WHERE status='active' AND world_id=%(w)s) AS active,
                   (SELECT count(*) FROM batches WHERE status='submitted') AS open_batches,
                   (SELECT count(*) FROM headlines WHERE safe IS FALSE) AS blocked_headlines
            """,
            {"w": CONFIG.world_id},
        )
        totals = dict(cur.fetchone())

        cur.execute(
            "SELECT id, turns_sent, posts_written, news_share, started_at, error "
            "FROM ticks ORDER BY id DESC LIMIT 10"
        )
        recent = [TickRow.model_validate(dict(r)) for r in cur.fetchall()]

        # cache_read == 0 across collected batches is the ONLY signal that a silent cache
        # invalidator has crept in — there is no error for it.
        cur.execute(
            """
            SELECT coalesce(sum(input_tokens), 0)       AS input_tokens,
                   coalesce(sum(output_tokens), 0)      AS output_tokens,
                   coalesce(sum(cache_read_tokens), 0)  AS cache_read_tokens,
                   coalesce(sum(cache_write_tokens), 0) AS cache_write_tokens,
                   count(*) FILTER (WHERE status = 'failed') AS failed_batches
              FROM batches
            """
        )
        usage = UsageOut.model_validate(dict(cur.fetchone()))

    return StatsOut(
        **totals,
        usage=usage,
        recent_ticks=recent,
        budget=BudgetOut(
            tick_budget=CONFIG.tick_budget,
            interval_minutes=CONFIG.tick_interval_minutes,
            turns_per_day=round(CONFIG.ticks_per_day * CONFIG.tick_budget),
        ),
    )
